- name: nginx and updating
  apt:
    name: nginx
    state: latest

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: replace default the with my copy
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

#- name: replace exporter
#  ansible.builtin.template:
#    src: exporter
#    dest: /etc/nginx/sites-enabled/exporter
#  notify: Restart nginx
