- name: adding an apt key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: add a repository into source list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: install grafana
  ansible.builtin.apt:
    name: grafana

- name: start grafana on boot
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes
  
- name: create a dictionary
  file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: grafana directory
  ansible.builtin.file:
    path: /opt/grafana/provisioning/{{ item }}
    state: directory
    recurse: yes
  loop:
    - dashboards/main
    - datasources

- name: add grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true

#- name: add dashboards
#  ansible.builtin.copy:
#    src: "{{ item }}"
#    dest: /opt/grafana/provisioning/dashboards/{{ item }}
#  loop:
#    - main.json
#    - mysql.json
#    - syslog.json
#  no_log: true

- name: adding dashboards.yaml
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/default.yaml

- name: adding datasourcesyaml
  ansible.builtin.template: 
    src: datasources.yaml.j2
    dest: /opt/grafana/provisioning/datasources/default.yaml