{
 "title": "main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "Bind@{{instance}}" },
    { "expr": "mysql_up", "legendFormat": "MySQL@{{instance}}" },
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "InfluxDB@{{instance}}"
    },
    { "expr": "nginx_up", "legendFormat": "Nginx@{{instance}}" },
    { "expr": "haproxy_up", "legendFormat": "HAproxy@{{instance}}" },
    { "expr": "keepalived_up", "legendFormat": "keepalived@{{instance}}" }
   ]
  },
  {
   "title": "Backend VM1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"DennisBykov-1:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Backend VM2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"DennisBykov-2:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "VM_CPU_load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keepalived VM1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"DennisBykov-1:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keepalived VM2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"DennisBykov-2:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VM memory usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes )*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "type A DNS queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Influx write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database Slects per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VM amonut of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}