- name: backup
  user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: create known hosts
  ansible.builtin.template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    mode: '644'