- name: Install docker container
  apt:
    name:
      - docker.io
      - python3-docker
    state: present
  register: docker_install

#- name: iptables-persistent 
#  apt:
#    name: iptables-persistent 

#- name: iptables-save -t mangle
#  shell: iptables-save -t mangle
#  when: docker_install.changed

#- name: /var/local/iptables.mangle
#  template:
#    src: iptables.mangle
#    dest: /var/local/iptables.mangle
#  when: docker_install.changed

#- name: Perform iptables-restore
#  community.general.iptables_state:
#    path: /var/local/iptables.mangle
#    state: restored
#    table: mangle
#  when: docker_install.changed
  
- name: Log into dockerhub
  community.docker.docker_login:
    username: "{{ docker_user }}"
    password: "{{ grafana_pass }}"

- name: Docker started
  service:
    name: docker
    state: started
    enabled: yes